spring:
  application:
    name: eduplan

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eduplan}
    username: ${DB_USERNAME:eduplan}
    password: ${DB_PASSWORD:eduplan}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


application:
  security:
    jwt:
      secret-key: eEWH1hVWy1pvEQD6Hx06Gzl9Odh6cZexFZzPfoLSHE8ARqBYNAiYLz7r7F1WEBHmE2EscRCy+sguVIdJEMpeTg==
      expiration: 86400000
      refresh-token:
        expiration: 604800000