spring:
  application:
    name: eduplan

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eduplan}
    username: ${DB_USERNAME:eduplan}
    password: ${DB_PASSWORD:eduplan}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  storage:
    type: local

application:
  security:
    password:
      strength: 8
    jwt:
      secret-key: ${JWT_SECRET_KEY:Zm9yLWRldmVsb3BtZW50LW9ubHktc2VjcmV0LWtleS0zMmJ5dGVzLW1pbmltdW0=}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}
