spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:tc:postgresql:17://localhost/test_db}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql